# This file generated by makedep.py
VERSION=0.8
PYTHON_SOURCES=\
	parser/tree_sitter.py \
	parser/runtime.py \
	parser/generated_source.py \
	parser/parser.py \
	parser/emacs.py \
	parser/wadler/runtime.py \
	parser/wadler/builder.py \
	parser/wadler/__init__.py \
	parser/__init__.py
