import tomllib


def main():
    with open("pyproject.toml", "rb") as f:
        result = tomllib.load(f)
    version = result["project"]["version"]
    includes = result["tool"]["pdm"]["build"]["includes"]
    with open("lrparser.mk", "w", encoding="utf-8") as f:
        f.write("# This file generated by makedep.py\n")
        f.write(f"VERSION={version}\n")
        f.write(f"PYTHON_SOURCES=\\\n\t{' \\\n\t'.join(includes)}\n")


if __name__ == "__main__":
    main()
